baseURL = "https://nekomeishi.github.io/blog/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "jeffprod"

publishDir = "docs"

[permalinks]
    post = "/:year/:filename"

[taxonomies]
    tag = "tags"
    archive = "archives"
